name: Hello World Workflow

# Когда запускать workflow
on:
  push:                    # При каждом push
    branches: [ main ]     # Только в ветку main
  pull_request:            # При создании/обновлении PR
    branches: [ main ]
  workflow_dispatch:       # Ручной запуск

# Задачи
jobs:
  hello-job:
    runs-on: ubuntu-latest  # Операционная система для выполнения
    
    steps:
    # Шаг 1: Получаем код из репозитория
    - name: Checkout code
      uses: actions/checkout@v4
    
    # Шаг 2: Выводим приветствие
    - name: Say Hello
      run: |
        echo "Hello, GitHub Actions!"
        echo "Current date: $(date)"
        echo "Repository: ${{ github.repository }}"
        echo "Branch: ${{ github.ref_name }}"
    
    # Шаг 3: Показываем информацию о системе
    - name: System Info
      run: |
        echo "OS: $(uname -a)"
        echo "Current directory: $(pwd)"
        echo "Files in directory:"
        ls -la

  # Второй job (выполняется параллельно с первым)
  parallel-job:
    runs-on: ubuntu-latest
    
    steps:
    - name: Parallel Task
      run: |
        echo "This job runs in parallel!"
        sleep 5
        echo "Parallel job finished!"

  # Третий job (выполняется после первого)
  dependent-job:
    runs-on: ubuntu-latest
    needs: hello-job  # Зависимость: ждет завершения hello-job
    
    steps:
    - name: Dependent Task
      run: |
        echo "This job runs after hello-job is completed!"
        echo "Status of hello-job: success!"